# Generated by Django 5.2 on 2025-04-22 08:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("stopped", "Stopped by User"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.FloatField(default=0.0)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("task_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PassiveReconResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dns_records", models.JSONField(blank=True, null=True)),
                ("server_info", models.JSONField(blank=True, null=True)),
                ("robots_txt", models.TextField(blank=True, null=True)),
                ("sitemap_xml", models.TextField(blank=True, null=True)),
                ("technologies", models.JSONField(blank=True, null=True)),
                ("response_headers", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passive_recon_result",
                        to="scanning.scan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrawlResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urls_discovered", models.JSONField(blank=True, null=True)),
                ("forms_discovered", models.JSONField(blank=True, null=True)),
                ("cookies", models.JSONField(blank=True, null=True)),
                ("pages_crawled", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crawl_result",
                        to="scanning.scan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScanConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("passive", "Passive Scan"),
                            ("active", "Active Scan"),
                            ("full", "Full Scan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("crawl_depth", models.IntegerField(default=2)),
                ("respect_robots_txt", models.BooleanField(default=True)),
                ("crawl_max_pages", models.IntegerField(default=100)),
                ("crawl_timeout", models.IntegerField(default=30)),
                ("scan_js_files", models.BooleanField(default=True)),
                ("scan_forms", models.BooleanField(default=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("request_delay", models.FloatField(default=0.5)),
                ("custom_headers", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_configurations",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scan",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scans",
                to="scanning.scanconfiguration",
            ),
        ),
        migrations.CreateModel(
            name="ScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="scanning.scan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Informational"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("parameter", models.CharField(blank=True, max_length=255, null=True)),
                ("evidence", models.TextField(blank=True, null=True)),
                ("confidence", models.FloatField(default=1.0)),
                ("remediation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilities",
                        to="scanning.scan",
                    ),
                ),
            ],
        ),
    ]
