# Generated by Django 5.2 on 2025-05-05 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AjaxSpiderResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urls_discovered", models.JSONField(blank=True, null=True)),
                ("forms_discovered", models.JSONField(blank=True, null=True)),
                ("ajax_requests", models.JSONField(blank=True, null=True)),
                ("javascript_objects", models.JSONField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.FloatField(default=0.0)),
                ("pages_crawled", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ajax_spider_result",
                        to="scanning.scan",
                    ),
                ),
            ],
        ),
    ]
