# Generated by Django 5.2 on 2025-05-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanning", "0002_ajaxspiderresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanconfiguration",
            name="min_confidence",
            field=models.FloatField(
                default=0.7, help_text="Minimum confidence level for findings (0.0-1.0)"
            ),
        ),
        migrations.AddField(
            model_name="scanconfiguration",
            name="nuclei_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scanconfiguration",
            name="reduce_false_positives",
            field=models.BooleanField(
                default=False,
                help_text="Use enhanced scanning tools to reduce false positives",
            ),
        ),
        migrations.AddField(
            model_name="scanconfiguration",
            name="sslyze_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scanconfiguration",
            name="use_nuclei",
            field=models.BooleanField(
                default=False, help_text="Use Nuclei for passive scanning"
            ),
        ),
        migrations.AddField(
            model_name="scanconfiguration",
            name="use_sslyze",
            field=models.BooleanField(
                default=True, help_text="Use SSLyze for SSL/TLS scanning"
            ),
        ),
        migrations.AddField(
            model_name="scanconfiguration",
            name="use_wappalyzer",
            field=models.BooleanField(
                default=True, help_text="Use Wappalyzer for technology detection"
            ),
        ),
        migrations.AddField(
            model_name="scanconfiguration",
            name="use_zap",
            field=models.BooleanField(
                default=False, help_text="Use OWASP ZAP for passive scanning"
            ),
        ),
        migrations.AddField(
            model_name="scanconfiguration",
            name="wappalyzer_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scanconfiguration",
            name="zap_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
