# Generated by Django 5.2 on 2025-05-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanning", "0003_scanconfiguration_min_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanconfiguration",
            name="allow_analyzer_fallbacks",
            field=models.BooleanField(
                default=True,
                help_text="Whether to allow fallback to built-in analyzers when external tools are unavailable",
            ),
        ),
        migrations.AddField(
            model_name="scanconfiguration",
            name="tool_preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Tool preferences for various analysis types",
            ),
        ),
    ]
