# Generated by Django 5.2 on 2025-05-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanning", "0004_scanconfiguration_allow_analyzer_fallbacks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanconfiguration",
            name="use_zap",
            field=models.BooleanField(
                default=True, help_text="Use OWASP ZAP for passive scanning"
            ),
        ),
    ]
