# Generated by Django 5.1.11 on 2025-08-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0005_alter_scanconfiguration_use_zap'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanconfiguration',
            name='use_zap_spider',
            field=models.BooleanField(default=True, help_text='Use ZAP spider for crawling (more advanced than custom crawler)'),
        ),
    ]
