# Generated by Django 5.1.11 on 2025-08-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0006_scanconfiguration_use_zap_spider'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanconfiguration',
            name='zap_spider_type',
            field=models.CharField(choices=[('traditional', 'Traditional Spider'), ('ajax', 'AJAX Spider'), ('both', 'Both Spiders')], default='ajax', help_text='Type of ZAP spider to use for crawling', max_length=20),
        ),
    ]
