# Generated by Django 5.2.5 on 2025-08-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0007_scanconfiguration_zap_spider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanconfiguration',
            name='crawl_depth',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='crawl_max_pages',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='crawl_timeout',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='request_delay',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='respect_robots_txt',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='scan_forms',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='scan_js_files',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='use_zap_spider',
            field=models.BooleanField(default=True, help_text='Use ZAP spider for crawling (only for active/full scans)'),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='zap_spider_type',
            field=models.CharField(choices=[('traditional', 'Traditional Spider'), ('ajax', 'AJAX Spider'), ('both', 'Both Spiders')], default='ajax', help_text='Type of ZAP spider to use for crawling (only for active/full scans)', max_length=20),
        ),
    ]
