# Generated by Django 5.2.5 on 2025-08-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0009_remove_active_scan_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlresult',
            name='scan',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='project',
        ),
        migrations.RemoveField(
            model_name='scanconfiguration',
            name='allow_analyzer_fallbacks',
        ),
        migrations.RemoveField(
            model_name='scanconfiguration',
            name='custom_headers',
        ),
        migrations.RemoveField(
            model_name='scanconfiguration',
            name='nuclei_config',
        ),
        migrations.RemoveField(
            model_name='scanconfiguration',
            name='reduce_false_positives',
        ),
        migrations.RemoveField(
            model_name='scanconfiguration',
            name='request_delay',
        ),
        migrations.RemoveField(
            model_name='scanconfiguration',
            name='sslyze_config',
        ),
        migrations.RemoveField(
            model_name='scanconfiguration',
            name='tool_preferences',
        ),
        migrations.RemoveField(
            model_name='scanconfiguration',
            name='use_zap',
        ),
        migrations.RemoveField(
            model_name='scanconfiguration',
            name='wappalyzer_config',
        ),
        migrations.RemoveField(
            model_name='scanconfiguration',
            name='zap_config',
        ),
        migrations.AddField(
            model_name='scan',
            name='target_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='request_timeout',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='use_zap_passive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='min_confidence',
            field=models.FloatField(default=0.7),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='scan_type',
            field=models.CharField(choices=[('passive', 'Passive Scan')], default='passive', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='use_nuclei',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='use_sslyze',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='use_wappalyzer',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='AjaxSpiderResult',
        ),
        migrations.DeleteModel(
            name='CrawlResult',
        ),
    ]
