# Generated by Django 5.2.5 on 2025-09-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0010_remove_crawlresult_scan_remove_scan_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanconfiguration',
            name='enable_ajax_spider',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='enable_spider',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='max_concurrent_requests',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='max_spider_depth',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='max_spider_duration',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='request_delay_ms',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='scan_timeout_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='test_authentication',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='test_authorization',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='test_command_injection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='test_csrf',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='test_file_inclusion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='test_path_traversal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='test_session_management',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='test_sql_injection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='test_xss',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='test_xxe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='use_zap_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='zap_active_scan_policy',
            field=models.CharField(default='Default Policy', max_length=100),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='zap_attack_strength',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('INSANE', 'Insane')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='scan_type',
            field=models.CharField(choices=[('passive', 'Passive Scan'), ('active', 'Active Scan'), ('comprehensive', 'Comprehensive Scan (Passive + Active)')], default='passive', max_length=20),
        ),
        migrations.CreateModel(
            name='ActiveScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spider_results', models.JSONField(blank=True, null=True)),
                ('ajax_spider_results', models.JSONField(blank=True, null=True)),
                ('urls_discovered', models.JSONField(blank=True, null=True)),
                ('forms_discovered', models.JSONField(blank=True, null=True)),
                ('attack_surface', models.JSONField(blank=True, null=True)),
                ('raw_findings', models.JSONField(blank=True, null=True)),
                ('authentication_tests', models.JSONField(blank=True, null=True)),
                ('session_analysis', models.JSONField(blank=True, null=True)),
                ('zap_scan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zap_spider_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zap_ajax_spider_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zap_active_scan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total_requests_made', models.IntegerField(default=0)),
                ('total_responses_received', models.IntegerField(default=0)),
                ('scan_duration_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_scan_result', to='scanning.scan')),
            ],
            options={
                'verbose_name': 'Active Scan Result',
                'verbose_name_plural': 'Active Scan Results',
            },
        ),
    ]
