# Generated by Django 5.2.6 on 2025-09-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0011_scanconfiguration_enable_ajax_spider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passivereconresult',
            name='enhanced_discovery',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
