# Generated by Django 5.2.6 on 2025-09-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0012_add_enhanced_discovery_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanconfiguration',
            name='discovery_timeout',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='max_directories',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='max_subdomains',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='max_wayback_urls',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='use_enhanced_discovery',
            field=models.BooleanField(default=True),
        ),
    ]
