# Generated by Django 5.2.6 on 2025-10-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0016_remove_vulnerability_attack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanconfiguration',
            name='sqlmap_level',
            field=models.IntegerField(default=1, help_text='SQLMap level (1-5)'),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='sqlmap_risk_level',
            field=models.IntegerField(default=1, help_text='SQLMap risk level (1-3)'),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='sqlmap_timeout',
            field=models.IntegerField(default=300, help_text='SQLMap timeout in seconds'),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='use_nosqlmap',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='use_sqlmap',
            field=models.BooleanField(default=True),
        ),
    ]
