# Generated by Django 5.2.7 on 2025-10-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0017_scanconfiguration_sqlmap_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanconfiguration',
            name='sqlmap_timeout',
            field=models.IntegerField(default=60, help_text='SQLMap timeout in seconds'),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='use_nosqlmap',
            field=models.BooleanField(default=False),
        ),
    ]
