# Generated by Django 5.2.7 on 2025-11-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0020_add_authentication_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('stopping', 'Stopping'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanconfiguration',
            name='parameter_fuzzing_values',
            field=models.JSONField(default=list, help_text='Custom parameter values to test'),
        ),
    ]
