# Generated by Django 5.2.8 on 2025-12-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0022_add_vulnerability_metadata_for_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanconfiguration',
            name='active_scan_timeout_minutes',
            field=models.IntegerField(default=30, help_text='Timeout for active scan phase in minutes'),
        ),
    ]
